### ISSUE TITLE
Thumbnails for social media

### ISSUE THREAD

**Issue by thisisjp** [mozzillation/checolo.re#23]

**Comment by thisisjp** [comment]
Facebook and Twitter thumbnails are in Figma > Social

**Comment by thisisjp** [comment]
@mozzillation se non mostriamo dati dinamici non saprei cos'altro mettere se non il logo su sfondo nero (qualsiasi altro colore darebbe un'impressione sbagliata), no?

**Comment by mozzillation** [comment]
> @mozzillation se non mostriamo dati dinamici non saprei cos'altro mettere se non il logo su sfondo nero (qualsiasi altro colore darebbe un'impressione sbagliata), no?

Yes, per ora teniamo lo sfondo nero, poi capiamo i dati "dinamici" come farli

**Comment by iamlucamilan** [comment]
![Twitter- FB Card](https://user-images.githubusercontent.com/834766/106248974-0784a900-6212-11eb-9cc8-298854349798.png)

**Comment by iamlucamilan** [comment]
Implemented at 3b98ed1dcda954d6a7ea313b4fcc3aac63c61312 but I've some issues with the twitter one. @mozzillation @edoguido can you take a look?
