### ISSUE TITLE
100vh background doesn't work on Safari iOS

### ISSUE THREAD

**Issue by thisisjp** [mozzillation/checolo.re#24]

**Comment by thisisjp** [comment]
![IMG_6B451F21D0D4-1](https://user-images.githubusercontent.com/2277990/106112255-4e5c9b00-614d-11eb-8335-2193067702e6.jpeg)

**Comment by mozzillation** [comment]
penso fosse voluto così, nel codice è `90vh`. @edoguido che ne sai tu di questa storia?

**Comment by edoguido** [comment]
Risolto con https://github.com/mozzillation/checolo.re/commit/12a7b5bca023d238b1797eda99c020066b33ce0e
