### ISSUE TITLE
Error on rendering privacy policy md file

### ISSUE THREAD

**Issue by iamlucamilan** [mozzillation/checolo.re#27]
![image](https://user-images.githubusercontent.com/834766/106369443-9ea44a80-6351-11eb-92e8-795cb63d4d4f.png)

**Comment by edoguido** [comment]
In what way is this a bug? Can you provide a bit of context?

**Comment by thisisjp** [comment]
@edoguido as @iamlucamilan shown in the attached screenshot, there's a missing render for nested lists. I simply changed the content to make it easier

**Comment by edoguido** [comment]
> there's a missing render for nested lists. I simply changed the content to make it easier

This happens because you are trying to render formatted text on a **pre** tag, which is used for rendering code/preformatted text, so bullet points and such won't be rendered as you'd normally expect.

I'll close this issue and accept @thisisjp 's PR
