### ISSUE TITLE
[suggerimento ux] Link a FAQ governo 

### ISSUE THREAD

**Issue by christian-mazzoleni** [mozzillation/checolo.re#30]
Alla fine della una pagina di una regione, dopo la lista di cose che posso fare in base al colore, attualmente è presente il link al sito ufficiale della regione. Se io ho bisogno di sapere più nello specifico alcune informazioni non chiare, che non ho trovato sulla vostra pagina, probabilmente dal sito della regione vado direttamente nelle FAQ del governo per cercare la risposta.

**Suggerimento:** inserire il link diretto alle FAQ del governo alla fine della pagina di una regione, così evito questo doppio passaggio.

**Comment by iamlucamilan** [comment]
Ciao Christian, grazie per il tuo commento. 
Il link alla pagina della FAQ del Governo lo puoi trovare sia nella pagina Info, dove era stato posizionato inizialmente, sia nel footer e quindi raggiungibile più facilmente da tutte le pagine. 👍
